Bristol SU Playground: BristolSU\Playground\Support\Events\Event Class Reference
BristolSU\Playground\Support\Events\Event Class Reference
Public Member Functions
getNameAttribute ()
getDescriptionAttribute ()
getEventInformation ()
getDataAttribute ()
Protected Attributes
$fillable
$casts
$appends
Detailed Description
Definition at line 8 of file Event.php.
Member Function Documentation
getDataAttribute()
BristolSU\Playground\Support\Events\Event::getDataAttribute ()
Test:
Definition at line 54 of file Event.php.
getDescriptionAttribute()
BristolSU\Playground\Support\Events\Event::getDescriptionAttribute ()
Definition at line 33 of file Event.php.
References BristolSU\Playground\Support\Events\Event\getEventInformation().
getEventInformation()
BristolSU\Playground\Support\Events\Event::getEventInformation ()
Definition at line 43 of file Event.php.
Referenced by BristolSU\Playground\Support\Events\Event\getDescriptionAttribute(), and BristolSU\Playground\Support\Events\Event\getNameAttribute().
getNameAttribute()
BristolSU\Playground\Support\Events\Event::getNameAttribute ()
Definition at line 23 of file Event.php.
References BristolSU\Playground\Support\Events\Event\getEventInformation().
Member Data Documentation
$appends
BristolSU\Playground\Support\Events\Event::$appends protected
Initial value:
= [
        'name', 'description'
    ]
Definition at line 19 of file Event.php.
$casts
BristolSU\Playground\Support\Events\Event::$casts protected
Initial value:
= [
        'data' => 'array'
    ]
Definition at line 15 of file Event.php.
$fillable
BristolSU\Playground\Support\Events\Event::$fillable protected
Initial value:
= [
        'module_instance_id', 'event', 'data'
    ]
Definition at line 11 of file Event.php.
The documentation for this class was generated from the following file:
app/Support/Events/Event.php