Bristol SU Playground: BristolSU\Playground\Providers\RouteServiceProvider Class Reference
BristolSU\Playground\Providers\RouteServiceProvider Class Reference
Public Member Functions
boot ()
map ()
Protected Member Functions
mapWebRoutes ()
mapApiRoutes ()
Protected Attributes
$namespace = 'BristolSU\Playground\Http\Controllers'
Detailed Description
Set up routing
Definition at line 16 of file RouteServiceProvider.php.
Member Function Documentation
boot()
BristolSU\Playground\Providers\RouteServiceProvider::boot ()
Boot routing
Route model binding for module permissions
Route model binding for module instance (without needing an activity)
Returns
void
Definition at line 34 of file RouteServiceProvider.php.
map()
BristolSU\Playground\Providers\RouteServiceProvider::map ()
Define the routes for the application.
Returns
void
Definition at line 53 of file RouteServiceProvider.php.
References BristolSU\Playground\Providers\RouteServiceProvider\mapApiRoutes(), and BristolSU\Playground\Providers\RouteServiceProvider\mapWebRoutes().
mapApiRoutes()
BristolSU\Playground\Providers\RouteServiceProvider::mapApiRoutes () protected
Define the "api" routes for the application.
These routes are typically stateless.
Returns
void
Definition at line 83 of file RouteServiceProvider.php.
Referenced by BristolSU\Playground\Providers\RouteServiceProvider\map().
mapWebRoutes()
BristolSU\Playground\Providers\RouteServiceProvider::mapWebRoutes () protected
Define the "web" routes for the application.
These routes all receive session state, CSRF protection, etc.
Returns
void
Definition at line 69 of file RouteServiceProvider.php.
Referenced by BristolSU\Playground\Providers\RouteServiceProvider\map().
Member Data Documentation
$namespace
BristolSU\Playground\Providers\RouteServiceProvider::$namespace = 'BristolSU\Playground\Http\Controllers' protected
Definition at line 25 of file RouteServiceProvider.php.
The documentation for this class was generated from the following file:
app/Providers/RouteServiceProvider.php