Bristol SU Playground: BristolSU\Playground\Http\Middleware\Authenticate Class Reference
BristolSU\Playground\Http\Middleware\Authenticate Class Reference
Public Member Functions
__construct (UserAuthentication $userAuthentication)
handle (Request $request, \Closure $next)
Protected Member Functions
unauthenticated ($request)
redirectTo ($request)
Private Attributes
$userAuthentication
Detailed Description
Check a user is authenticated.
Return an unauthenticated response if they are not
Definition at line 14 of file Authenticate.php.
Constructor & Destructor Documentation
__construct()
BristolSU\Playground\Http\Middleware\Authenticate::__construct (UserAuthentication $userAuthentication)
Parameters
UserAuthentication $userAuthentication Authentication to get the user from
Definition at line 26 of file Authenticate.php.
References BristolSU\Playground\Http\Middleware\Authenticate\$userAuthentication.
Member Function Documentation
handle()
BristolSU\Playground\Http\Middleware\Authenticate::handle (Request $request, \Closure $next)
Test if the user is authenticated
Parameters
Request $request Request object
\Closure $next Next middleware callback
Returns
mixed
Exceptions
AuthenticationException If not authenticated
Definition at line 40 of file Authenticate.php.
References BristolSU\Playground\Http\Middleware\Authenticate\unauthenticated().
redirectTo()
BristolSU\Playground\Http\Middleware\Authenticate::redirectTo ($request) protected
Get the path the user should be redirected to when they are not authenticated.
Parameters
\Illuminate\Http\Request $request
Returns
string|null
Definition at line 71 of file Authenticate.php.
Referenced by BristolSU\Playground\Http\Middleware\Authenticate\unauthenticated().
unauthenticated()
BristolSU\Playground\Http\Middleware\Authenticate::unauthenticated ($request) protected
Handle an unauthenticated user.
Parameters
\Illuminate\Http\Request $request
array $guards
Returns
void
Exceptions
Definition at line 58 of file Authenticate.php.
References BristolSU\Playground\Http\Middleware\Authenticate\redirectTo().
Referenced by BristolSU\Playground\Http\Middleware\Authenticate\handle().
Member Data Documentation
$userAuthentication
BristolSU\Playground\Http\Middleware\Authenticate::$userAuthentication private
Definition at line 21 of file Authenticate.php.
Referenced by BristolSU\Playground\Http\Middleware\Authenticate\__construct().
The documentation for this class was generated from the following file:
app/Http/Middleware/Authenticate.php